apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: mysql-pod
    app: wordpress
  name: mysql-pod
spec:
  volumes:
  - name: mysql-pv-claim
    persistentVolumeClaim:
      claimName: mysql-pv-claim
  containers:
  - image: mysql
    name: mysql-pod
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    ports:
    - containerPort: 3306
    volumeMounts:
    - name: mysql-pv-claim
      mountPath: /var/lib/mysql
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
