apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: wordpress-pod
    app: wordpress
  name: wordpress-pod
spec:
  containers:
  - image: wordpress
    name: wordpress-pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
